### ISSUE TITLE
sum on expandoobject

### ISSUE THREAD

**Issue by kaiwachter** [dkackman/SqlLinq#3]
Hi Folks,
awesome work. But actually i am facing a problem.
i modified your test case a bit, but it gives exception (no method found)
i just changed the SQL statement to:
SELECT sum(Id), City FROM this group by City

How can i achieve to make aggegate function on a Expandoobject of Dynamicobject?
        [TestMethod]
        public void ExpandoAsSource()
        {
            var customers = new List<dynamic>();
            for (int i = 0; i < 10; ++i)
            {
                string iter = i.ToString();
                for (int j = 0; j < 3; ++j)
                {
                    dynamic customer = new ExpandoObject();
                    customer.City = "Chicago" + iter;
                    customer.Id = i;
                    customer.Name = "Name" + iter;
                    customer.CompanyName = "Company" + iter + j.ToString();

```
                customers.Add(customer);
            }
        }

        var result = customers.Cast<IDictionary<string, object>>().Query<IDictionary<string, object>, dynamic>("SELECT sum(Id), City FROM this group by City").Cast<IDictionary<string, object>>();
```

}

**Comment by dkackman** [comment]
This is a tricky one. The current design reflects on the generic type arguments for the source and result to figure out the types of the various fields to query, compute and return. Dynamic of course doesn't have reflectable type information so the crux is that the expression generation fails because it doesn't know it is supposed to can Sum<int>(). Adding a cast or convert operator to the sql syntax is my current thinking on how communicate the desired type information.

**Comment by dkackman** [comment]
stale
